
name: CI workflow

on:
  push:
    branches:
      - main # Specify the branch name directly here
  pull_request:
    branches:
      - main # Specify the branch name directly here

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim # Correct the indentation here
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Updated to v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
